### ISSUE TITLE
Writing to a file not writing all the documents 

### ISSUE THREAD

**Issue by akshay2604** [bentonam/fakeit#150]
Writing something like this 
`fakeit directory output products.yaml --count 3 `
results in 
`output/user_undefined.json`
```
{
  "_id": "591165ca80ff8eed1a18bfe9",
  "xAddr": {
    "xCO": "Suite 885",
    "xLine1": "Lisette Court",
    "xLine2": "477 Reese Mount",
    "xCity": "Port Chynafurt",
    "xSOP": "Delaware",
    "xPostCode": "77249",
    "xCountry": "Guernsey"
  }
}"
  }
}  }
}
```

However running `fakeit console products.yaml --count 3` is producing the desired output.
```
[
  {
    "_id": "591166ac3897c9ed43d495d9",
    "xAddr": {
      "xCO": "Suite 730",
      "xLine1": "Brayan Heights",
      "xLine2": "0812 Streich Run",
      "xCity": "Carmellaview",
      "xSOP": "Mississippi",
      "xPostCode": "75998-1282",
      "xCountry": "Monaco"
    }
  },
  {
    "_id": "591166ac3897c9ed43d495da",
    "xAddr": {
      "xCO": "Apt. 410",
      "xLine1": "Jaden Junction",
      "xLine2": "72132 Trever Spur",
      "xCity": "Pourosview",
      "xSOP": "New York",
      "xPostCode": "20663",
      "xCountry": "Jersey"
    }
  },
  {
    "_id": "591166ac3897c9ed43d495db",
    "xAddr": {
      "xCO": "Suite 702",
      "xLine1": "Greenholt Forks",
      "xLine2": "732 Rolando Garden",
      "xCity": "Joshstad",
      "xSOP": "Tennessee",
      "xPostCode": "85367",
      "xCountry": "Timor-Leste"
    }
  }
]
```

File is saved with UTF-8 encoding.

**Comment by tjbenton** [comment]
Can you provide the `products.yaml` here and if there're other dependencies could you create a gist and just post the link.

**Comment by akshay2604** [comment]
`products.yaml`
```
name: Products
type: object
key:
  data:
    build: `user_${this.user_id}`
data:
  inputs: /Users/sahusoft/Sites/projects/cloud9pg-api/input/product.json, /Users/sahusoft/Sites/projects/cloud9pg-api/input/abc.json
  pre_run: |
    console.log("inputs", inputs)
    globals.user_counter = 0;
properties:
  _id:
    type: string
    description: The document id
    data:
      build: |
        return require('/Users/sahusoft/Sites/projects/cloud9pg-api/node_modules/mongoose').Types.ObjectId()
  xAddr:
    type: object
    properties:
      xCO:
        data:
          fake: '{{address.secondaryAddress}}'
      xLine1:
        data:
          fake: '{{address.secondaryAddress}}'
      xLine2:
        data:
          fake: '{{address.streetAddress}}'
      xCity:
        data:
          fake: '{{address.city}}'
      xSOP:
        data:
          fake: '{{address.state}}'
      xPostCode:
        data:
          fake: '{{address.zipCode}}'
      xCountry:
        data:
          fake: '{{address.country}}'
```

**Comment by tjbenton** [comment]
So It looks like the problem is the way you are creating the `key` which is what determines what the name of the document is. 

```yaml
key:
  data:
    build: `user_${this.user_id}`
```

Here you're returning a key of `user_undefined` every time which is why you're only seeing 1 file generated because each document that's generated overwrites the last one. The reason for this is that `this.user_id` isn't defined because you haven't defined that property yet

```
properties:
  _id:
    type: string
    description: The document id
    data:
      build: require('/Users/sahusoft/Sites/projects/cloud9pg-api/node_modules/mongoose').Types.ObjectId()
  user_id: 
    type: string
    data:
      build: faker.random.uuid()
```
Here's what the output is after adding the `user_id` property.

![screen shot 2017-05-09 at 9 17 46 am](https://cloud.githubusercontent.com/assets/4776422/25852745/66b33e38-3498-11e7-8e1c-aad323d5eb9a.jpg)




The following doesn't have anything to do with the problem just a helpful tip that will hopefully make things easier for you.

Also it looks like you're in the folder of `/Users/sahusoft/Sites/projects/cloud9pg-api` and the way this project works is by using relative paths. So instead of specifying the absolute path which will only work on your computer it's better to specify them like this.

```yaml
data:
  inputs: 
    - input/product.json
    - input/abc.json
```

Also node works very similarly. So for the `properties._id.data.build` all you need is `require('mongoose').Types.ObjectId()` because node will look inside of the `node_modules` directory for the folder `mongoose` and then look at it's `package.json` to find the main file to import.
