### ISSUE TITLE
post_build steps not being run in referenced array item object definitions

### ISSUE THREAD

**Issue by ghost** [bentonam/fakeit#63]
When defining array items by a referenced definition, the post_build step does not get executed.  The following is an example with output:

**Array Property Definition:**

``` yaml
tags:
  type: array
  description: An array of tags describing the prospect and their interests
  items:
    $ref: '#/definitions/Tags'
    data:
      min: 0
      max: 10
```

**Items Definition**

``` yaml
Tags:
  type: string
  data:
    pre_build: "console.log('pre');"
    build: >
      console.log('build');
      return chance.word();
    post_build: "console.log('post');"
```

**Run command**
`fakeit -m prospects.yaml -i input/ -n 5 -d output/`

**Output**
`Generating 5 documents for Prospects model
pre
build
pre
build
pre
build
pre
build
pre
build
pre
build
pre
build
pre
build
pre
build
pre
build
pre
build
pre
build
pre
build
pre
build
pre
build
pre
build
pre
build
pre
build
pre
build
pre
build`
